//! Export-pack assembly, parsing, and the `spec/03-export-pack.md` §6 verdicts.
//!
//! The fixtures under `testdata/packs/` are inputs for `vigil-verify`, which
//! does not exist yet. What these tests assert now is that each fixture *is what
//! the spec says it is*: the honest pack matches the hand-built golden vector
//! byte-for-byte, and each tamper case, run through `vigil-ledger`'s own
//! verification path (`verify_chain`, `Dag::build`, `bracket`), produces the
//! distinct §6.5 verdict it is meant to. Keeping those three verdicts
//! distinguishable is the point of the taxonomy.

#[path = "../testsupport/pack_scenarios.rs"]
mod pack_scenarios;

use std::collections::{BTreeMap, BTreeSet};

use ed25519_dalek::SigningKey;
use vigil_core::{Hash, Hlc, Object, Observation, ObservationBody, SignedObject, public_key};
use vigil_ledger::{
    ChainVerification, ChainViolation, Dag, MemoryStore, Quarantine, Store, WindowEdge, append,
    export_pack, parse_pack, verify_chain,
};

use pack_scenarios::{Honest, org_key};

const GOLDEN: &str = include_str!("../../../testdata/vectors/pack-worked-example.json");
const HONEST: &[u8] = include_bytes!("../../../testdata/packs/honest.vgl");
const T1: &[u8] = include_bytes!("../../../testdata/packs/t1-flipped-byte.vgl");
const T2: &[u8] = include_bytes!("../../../testdata/packs/t2-resigned-genesis.vgl");
const T3: &[u8] = include_bytes!("../../../testdata/packs/t3-dropped-anchor.vgl");
const FORK_WITNESS: &[u8] = include_bytes!("../../../testdata/packs/fork-witness.vgl");
const EARLIEST_HELD: &[u8] = include_bytes!("../../../testdata/packs/earliest-held.vgl");

fn golden_file_hex() -> String {
    let v: serde_json::Value = serde_json::from_str(GOLDEN).expect("golden vector is JSON");
    v["file_hex"].as_str().expect("file_hex").to_owned()
}

/// Rebuild a store from a parsed pack's *surviving* objects — the input to
/// `spec/03` §5 steps 4–6.
fn store_from_pack(pack: &vigil_ledger::PackContents) -> MemoryStore {
    let mut s = MemoryStore::new();
    for (_, obs, sig) in pack.valid_observations() {
        s.put_observation(obs, sig).expect("put");
    }
    for (_, att, sig) in pack.valid_attestations() {
        s.put_attestation(att, sig).expect("put");
    }
    s
}

// ---------------------------------------------------------------------------
// The fixtures are reproducible, and the honest one matches the golden vector
// ---------------------------------------------------------------------------

#[test]
fn every_fixture_matches_its_checked_in_bytes() {
    let on_disk: BTreeMap<&str, &[u8]> = BTreeMap::from([
        ("honest.vgl", HONEST),
        ("t1-flipped-byte.vgl", T1),
        ("t2-resigned-genesis.vgl", T2),
        ("t3-dropped-anchor.vgl", T3),
        ("fork-witness.vgl", FORK_WITNESS),
        ("earliest-held.vgl", EARLIEST_HELD),
    ]);
    for (name, bytes) in pack_scenarios::all_fixtures() {
        assert_eq!(
            hex::encode(&bytes),
            hex::encode(on_disk[name]),
            "{name}: regenerated bytes differ from the checked-in fixture — \
             run `cargo run -p vigil-ledger --example gen_packs` and review the diff"
        );
    }
}

/// The exporter's honest pack is byte-identical to the golden vector, which was
/// built by hand from the `spec/03` §2.2 envelope table with no call to this
/// code (`testdata/vectors/pack-worked-example.json`, generated by
/// `vigil-core`'s `gen_vectors`).
#[test]
fn honest_pack_matches_the_hand_built_golden_vector() {
    assert_eq!(hex::encode(HONEST), golden_file_hex());
    assert_eq!(
        hex::encode(pack_scenarios::honest_pack()),
        golden_file_hex()
    );
    assert_eq!(HONEST.len(), 775, "spec/03 §6.3: 775-byte file");
}

// ---------------------------------------------------------------------------
// §6.4 — the honest verification result
// ---------------------------------------------------------------------------

#[test]
fn honest_pack_verifies_exactly_as_spec_6_4_states() {
    let h = Honest::build();
    let pack = parse_pack(HONEST).expect("honest pack parses");

    // Step 1–2: envelope + per-object self-check.
    assert_eq!(pack.wire_version, 1);
    assert_eq!(pack.org, org_key());
    assert_eq!(pack.invalid_object_count, 0, "all three objects self-check");
    assert_eq!(pack.claims, vec![h.a0.id()]);

    // Step 3: no fork proofs.
    assert!(pack.fork_proofs.is_empty());

    // Step 4: chain of A over {A@0, A@1} is Verified.
    let store = store_from_pack(&pack);
    assert_eq!(
        verify_chain(&store, &public_key(&h.a)).unwrap(),
        ChainVerification::Verified
    );

    // Steps 5–6: bracket(A@0) is sealed by U, depth 1, open below to genesis.
    let dag = Dag::build(&store, &Quarantine::new()).unwrap();
    let br = dag.bracket(h.a0.id()).expect("A@0 is a vertex");
    assert!(br.sealed);
    assert_eq!(br.upper_bound, Some(h.u.id()));
    assert_eq!(br.witness_depth, 1);
    assert_eq!(br.lower_bound, None);
    assert_eq!(br.unwitnessed_window.lower, WindowEdge::Genesis);
    assert_eq!(
        br.unwitnessed_window.upper,
        WindowEdge::Attestation(h.u.id())
    );
    assert!(!br.disputed);
}

// ---------------------------------------------------------------------------
// §6.5 — the three tamper verdicts, distinct and named
// ---------------------------------------------------------------------------

/// T1: one flipped byte removes the object. The claim then names an id no
/// surviving object has, and A's chain is `Incomplete { missing: [0] }` — not a
/// forgery, an absence.
#[test]
fn t1_flipped_byte_is_claim_absent_and_incomplete_chain() {
    let h = Honest::build();
    let pack = parse_pack(T1).expect("T1 still parses — the envelope is intact");

    assert_eq!(
        pack.invalid_object_count, 1,
        "the flipped A@0 fails its self-check"
    );
    assert_eq!(pack.claims, vec![h.a0.id()]);
    assert!(
        pack.valid_observations().all(|(id, _, _)| id != h.a0.id()),
        "no surviving object has the claimed id — claim unverifiable"
    );

    let store = store_from_pack(&pack);
    match verify_chain(&store, &public_key(&h.a)).unwrap() {
        ChainVerification::Incomplete { missing } => assert_eq!(missing, vec![0]),
        other => panic!("expected Incomplete {{ missing: [0] }}, got {other:?}"),
    }
}

/// T2: a validly re-signed genesis. Every object self-checks, but the hash chain
/// does not close — `BrokenLink` against A's key, with the fields §6.5 names.
#[test]
fn t2_resigned_genesis_is_a_broken_link() {
    let h = Honest::build();
    let pack = parse_pack(T2).expect("T2 parses");
    assert_eq!(
        pack.invalid_object_count, 0,
        "A@0″ carries a valid signature"
    );

    let a0pp_id = pack_scenarios::t2_resigned_genesis_id();
    assert_eq!(
        a0pp_id.to_string(),
        "7ecd2314322d98e1a2efde2db4abd4d8dfed085ed4ead71aad776e3e571de718",
        "spec/03 §6.5 T2 states this id for the re-signed genesis"
    );

    let store = store_from_pack(&pack);
    match verify_chain(&store, &public_key(&h.a)).unwrap() {
        ChainVerification::Violated(vs) => {
            assert_eq!(vs.len(), 1);
            match &vs[0] {
                ChainViolation::BrokenLink {
                    author,
                    seq,
                    entry,
                    claimed_prev,
                    predecessor,
                } => {
                    assert_eq!(*author, public_key(&h.a));
                    assert_eq!(*seq, 1);
                    assert_eq!(*entry, h.a1.id());
                    assert_eq!(*claimed_prev, Some(h.a0.id()));
                    assert_eq!(predecessor, &vec![a0pp_id]);
                }
                other => panic!("expected BrokenLink, got {other:?}"),
            }
        }
        other => panic!("expected Violated(BrokenLink), got {other:?}"),
    }

    // And the claim still names the original genesis, which is absent.
    assert!(pack.valid_observations().all(|(id, _, _)| id != h.a0.id()));
}

/// T3: drop the anchor. Every object self-checks and A's chain is `Verified`
/// (genesis only), but `U` anchors nothing held, so `A@0` comes out
/// **unwitnessed** — the conservative outcome (invariant I5).
#[test]
fn t3_dropped_anchor_is_unwitnessed_via_unanchored_attestation() {
    let h = Honest::build();
    let pack = parse_pack(T3).expect("T3 parses");
    assert_eq!(pack.invalid_object_count, 0);
    assert_eq!(
        pack.valid_observations().count(),
        1,
        "only A@0 survives in observations"
    );
    assert_eq!(pack.valid_attestations().count(), 1, "U is still carried");

    let store = store_from_pack(&pack);
    assert_eq!(
        verify_chain(&store, &public_key(&h.a)).unwrap(),
        ChainVerification::Verified,
        "genesis-only chain, complete to the highest held"
    );

    let dag = Dag::build(&store, &Quarantine::new()).unwrap();
    let br = dag.bracket(h.a0.id()).expect("A@0 is a vertex");
    assert!(!br.sealed, "U seals nothing — its subject_head is not held");
    assert_eq!(br.upper_bound, None);
    assert_eq!(br.witness_depth, 0);
    assert_eq!(
        br.unwitnessed_window.upper,
        WindowEdge::VerificationMoment,
        "window open above to the verification moment"
    );
}

/// The three verdicts are genuinely different objects — a regression that
/// collapsed any two into one would defeat the taxonomy.
#[test]
fn the_three_tamper_verdicts_are_pairwise_distinct() {
    let h = Honest::build();
    let a = public_key(&h.a);
    let verdicts: Vec<ChainVerification> = [T1, T2, T3]
        .iter()
        .map(|p| verify_chain(&store_from_pack(&parse_pack(p).unwrap()), &a).unwrap())
        .collect();
    assert_ne!(verdicts[0], verdicts[1]);
    assert_ne!(verdicts[0], verdicts[2]);
    assert_ne!(verdicts[1], verdicts[2]);
}

// ---------------------------------------------------------------------------
// Fork proof against the witness (§3.4 / spec/02 §6.5)
// ---------------------------------------------------------------------------

#[test]
fn fork_witness_pack_carries_the_proof_and_the_seal_drops_under_quarantine() {
    let h = Honest::build();
    let pack = parse_pack(FORK_WITNESS).expect("fork-witness pack parses");

    // §3.4: the proof against the sealing witness is carried.
    assert_eq!(pack.fork_proofs.len(), 1);
    let checked = pack.fork_proofs[0].check().expect("proof self-verifies");
    assert_eq!(checked.key, public_key(&h.w), "convicts the witness W");
    assert_eq!(pack.invalid_object_count, 0);

    // Minimisation (§4): W's own equivocating entries are not carried — they are
    // not reachable from the claim.
    assert!(
        pack.valid_observations()
            .all(|(_, o, _)| o.author == public_key(&h.a)),
        "only A's chain segment travels, never the witness's"
    );

    let store = store_from_pack(&pack);

    // Without the quarantine the seal stands (this is the ablation baseline)...
    let open = Dag::build(&store, &Quarantine::new()).unwrap();
    assert!(open.bracket(h.a0.id()).unwrap().sealed);

    // ...and once W is quarantined on the carried proof, U stops sealing and
    // A@0 is reported unwitnessed (spec/02 §6.5) — what vigil-verify will do.
    let mut q = Quarantine::new();
    q.apply(&checked);
    let held = Dag::build(&store, &q).unwrap();
    assert!(!held.bracket(h.a0.id()).unwrap().sealed);
}

// ---------------------------------------------------------------------------
// EarliestHeld (§3.5)
// ---------------------------------------------------------------------------

#[test]
fn earliest_held_pack_omits_the_low_sequence_numbers() {
    let a = public_key(&SigningKey::from_bytes(&pack_scenarios::seed_a()));
    let pack = parse_pack(EARLIEST_HELD).expect("earliest-held pack parses");
    assert_eq!(pack.invalid_object_count, 0);
    assert_eq!(pack.claims, vec![pack_scenarios::earliest_held_claim()]);

    // §3.5: the marker is the absence of the low seqs, not a flag.
    let seqs: BTreeSet<u64> = pack
        .valid_observations()
        .filter(|(_, o, _)| o.author == a)
        .map(|(_, o, _)| o.seq)
        .collect();
    assert_eq!(seqs, BTreeSet::from([3, 4]));
    assert!(
        !seqs.contains(&0) && !seqs.contains(&1) && !seqs.contains(&2),
        "A@0..A@2 are not in the pack"
    );

    // A chain check over the carried segment is Incomplete, never Verified.
    let store = store_from_pack(&pack);
    match verify_chain(&store, &a).unwrap() {
        ChainVerification::Incomplete { missing } => assert_eq!(missing, vec![0, 1, 2]),
        other => panic!("expected Incomplete {{ missing: [0,1,2] }}, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// Assembly: minimisation, reachability, determinism
// ---------------------------------------------------------------------------

/// §3.3 / §4 — the pack carries exactly the claim's reachable closure: A@0, A@1,
/// and U. Nothing more.
#[test]
fn export_carries_exactly_the_reachable_closure() {
    let h = Honest::build();
    let pack = parse_pack(&pack_scenarios::honest_pack()).unwrap();

    let obs: BTreeSet<Hash> = pack.valid_observations().map(|(id, _, _)| id).collect();
    let att: BTreeSet<Hash> = pack.valid_attestations().map(|(id, _, _)| id).collect();
    assert_eq!(obs, BTreeSet::from([h.a0.id(), h.a1.id()]));
    assert_eq!(att, BTreeSet::from([h.u.id()]));
}

/// §4 — an unrelated observation in the store is not evidence for the claim and
/// MUST NOT appear in the pack.
#[test]
fn export_excludes_records_not_reachable_from_a_claim() {
    let h = Honest::build();
    let mut store = h.store();

    // A stranger writes an entirely unrelated record, and A writes a later entry
    // no attestation in the pack reaches.
    let stranger = SigningKey::from_bytes(&pack_scenarios::seed_stranger());
    let s0 = {
        Observation {
            author: public_key(&stranger),
            site: pack_scenarios::SITE,
            prev: None,
            seq: 0,
            hlc: Hlc::new(1_700_000_000_000, 0),
            body: ObservationBody::Note {
                text: "unrelated: canteen roster for Tuesday".to_owned(),
            },
            geo: None,
            acks: BTreeSet::new(),
        }
    };
    append(&mut store, &s0, &s0.sign(&stranger)).unwrap();
    let a2 = {
        Observation {
            author: public_key(&h.a),
            site: pack_scenarios::SITE,
            prev: Some(h.a1.id()),
            seq: 2,
            hlc: Hlc::new(1_700_000_200_000, 0),
            body: ObservationBody::Note {
                text: "later, unwitnessed entry".to_owned(),
            },
            geo: None,
            acks: BTreeSet::new(),
        }
    };
    append(&mut store, &a2, &a2.sign(&h.a)).unwrap();

    let pack =
        parse_pack(&export_pack(&store, &Quarantine::new(), org_key(), &[h.a0.id()]).unwrap())
            .unwrap();
    let obs: BTreeSet<Hash> = pack.valid_observations().map(|(id, _, _)| id).collect();
    assert!(
        !obs.contains(&s0.id()),
        "the stranger's record is not carried"
    );
    assert!(
        !obs.contains(&a2.id()),
        "A@2 is past the furthest anchored seq (1) and is not carried"
    );
    assert_eq!(obs, BTreeSet::from([h.a0.id(), h.a1.id()]));

    // The pack is byte-identical to the one built without the noise.
    assert_eq!(
        hex::encode(export_pack(&store, &Quarantine::new(), org_key(), &[h.a0.id()]).unwrap()),
        hex::encode(pack_scenarios::honest_pack())
    );
}

/// §2.3 — assembly is deterministic: the same claims over the same held set
/// produce byte-identical output, and adding unreachable noise never changes it.
#[test]
fn export_is_deterministic() {
    let h = Honest::build();
    let a = export_pack(&h.store(), &Quarantine::new(), org_key(), &[h.a0.id()]).unwrap();
    let b = export_pack(&h.store(), &Quarantine::new(), org_key(), &[h.a0.id()]).unwrap();
    assert_eq!(a, b);
}

#[cfg(not(target_family = "wasm"))]
mod property {
    use super::*;
    use proptest::prelude::*;

    proptest! {
        /// Unreachable observations added to the store in any number, with any
        /// bodies, never change the exported pack (§2.3, §4).
        #[test]
        fn noise_never_perturbs_the_pack(texts in proptest::collection::vec("[a-z ]{1,40}", 0..12)) {
            let h = Honest::build();
            let mut store = h.store();
            for (i, text) in texts.iter().enumerate() {
                let sk = SigningKey::from_bytes(&[0x90 ^ (i as u8); 32]);
                let o = Observation {
                    author: public_key(&sk),
                    site: pack_scenarios::SITE,
                    prev: None,
                    seq: 0,
                    hlc: Hlc::new(1_700_000_000_000, 0),
                    body: ObservationBody::Note { text: text.clone() },
                    geo: None,
                    acks: BTreeSet::new(),
                };
                append(&mut store, &o, &o.sign(&sk)).unwrap();
            }
            let pack = export_pack(&store, &Quarantine::new(), org_key(), &[h.a0.id()]).unwrap();
            prop_assert_eq!(hex::encode(pack), hex::encode(pack_scenarios::honest_pack()));
        }
    }
}
