//! Two obligations from `spec/03-export-pack.md` §8:
//!
//! 1. **The two traversals agree.** `vigil-verify`'s independently recomputed
//!    bracket equals `vigil-ledger`'s `bracket()` over the same object set, on
//!    honest input. Since this crate may not link `vigil-ledger`, the ledger's
//!    side is the checked-in `testdata/packs/expected/*.json`, generated by
//!    `cargo run -p vigil-ledger --example gen_pack_verdicts`. Two separate
//!    implementations of the DAG traversal reaching the same verdict is the
//!    whole reason this crate exists.
//!
//! 2. **No pack byte-string panics.** A pack is a file from an untrusted party
//!    (`spec/01` §8), so every path from raw bytes to a verdict is fuzzed. A
//!    panic here is exactly as severe as accepting a bad signature. These are
//!    `proptest` properties rather than a coverage-guided fuzzer for the same
//!    reason `vigil-core`'s `decode_robustness.rs` gives: an unrun fuzzer proves
//!    nothing, and what runs on every commit is worth more. A `cargo-fuzz`
//!    target over [`vigil_verify::verify`] belongs here too and would be a
//!    strict superset.

#![cfg(not(target_family = "wasm"))]

use proptest::prelude::*;
use serde_json::Value;
use vigil_core::{Hash, PubKey};
use vigil_verify::{ClaimOutcome, WindowEdge, parse_pack, verify};

const HONEST: &[u8] = include_bytes!("../../../testdata/packs/honest.vgl");
const T1: &[u8] = include_bytes!("../../../testdata/packs/t1-flipped-byte.vgl");
const T2: &[u8] = include_bytes!("../../../testdata/packs/t2-resigned-genesis.vgl");
const T3: &[u8] = include_bytes!("../../../testdata/packs/t3-dropped-anchor.vgl");
const FORK_WITNESS: &[u8] = include_bytes!("../../../testdata/packs/fork-witness.vgl");
const EARLIEST_HELD: &[u8] = include_bytes!("../../../testdata/packs/earliest-held.vgl");

const EXPECT_HONEST: &str = include_str!("../../../testdata/packs/expected/honest.json");
const EXPECT_T3: &str = include_str!("../../../testdata/packs/expected/t3-dropped-anchor.json");
const EXPECT_FORK: &str = include_str!("../../../testdata/packs/expected/fork-witness.json");

fn org() -> PubKey {
    PubKey(
        hex::decode("d04ab232742bb4ab3a1368bd4615e4e6d0224ab71a016baf8520a332c9778737")
            .unwrap()
            .try_into()
            .unwrap(),
    )
}

fn hash(s: &str) -> Hash {
    Hash(hex::decode(s).unwrap().try_into().unwrap())
}

fn opt_hash(v: &Value) -> Option<Hash> {
    v.as_str().map(hash)
}

fn edge(v: &Value) -> WindowEdge {
    match v {
        Value::String(s) if s == "genesis" => WindowEdge::Genesis,
        Value::String(s) if s == "verification_moment" => WindowEdge::VerificationMoment,
        Value::Object(m) => WindowEdge::Attestation(hash(m["attestation"].as_str().unwrap())),
        other => panic!("unexpected window edge in expected fixture: {other}"),
    }
}

/// Assert `vigil-verify`'s bracket for the fixture's single claim matches the
/// `vigil-ledger`-generated expected verdict field for field.
fn assert_agrees(pack: &[u8], expected_json: &str) {
    let expected: Value = serde_json::from_str(expected_json).expect("expected fixture is JSON");
    let report = verify(pack, org()).expect("fixture pack parses");

    // Chain verification agrees.
    let chain = &expected["chain"];
    let got_chain = &report.chains[0].1;
    match chain {
        Value::String(s) if s == "verified" => {
            assert!(matches!(
                got_chain,
                vigil_verify::ChainVerification::Verified
            ))
        }
        Value::String(s) if s == "violated" => assert!(got_chain.is_violated()),
        Value::Object(m) => {
            let want: Vec<u64> = m["incomplete"]
                .as_array()
                .unwrap()
                .iter()
                .map(|x| x.as_u64().unwrap())
                .collect();
            assert_eq!(
                got_chain,
                &vigil_verify::ChainVerification::Incomplete { missing: want }
            );
        }
        other => panic!("bad chain in expected fixture: {other}"),
    }

    let b = &expected["bracket"];
    assert_eq!(report.claims.len(), 1);
    let ClaimOutcome::Bracketed(got) = &report.claims[0].outcome else {
        panic!("expected a bracketed claim");
    };

    assert_eq!(got.observation, hash(b["observation"].as_str().unwrap()));
    assert_eq!(got.sealed, b["sealed"].as_bool().unwrap(), "sealed");
    assert_eq!(
        u64::from(got.witness_depth),
        b["witness_depth"].as_u64().unwrap(),
        "witness_depth"
    );
    assert_eq!(got.upper_bound, opt_hash(&b["upper_bound"]), "upper_bound");
    assert_eq!(got.lower_bound, opt_hash(&b["lower_bound"]), "lower_bound");
    assert_eq!(
        got.unwitnessed_window.lower,
        edge(&b["window_lower"]),
        "window lower edge"
    );
    assert_eq!(
        got.unwitnessed_window.upper,
        edge(&b["window_upper"]),
        "window upper edge"
    );
    assert_eq!(got.disputed, b["disputed"].as_bool().unwrap(), "disputed");
}

#[test]
fn independent_traversal_agrees_with_the_ledger_on_the_honest_pack() {
    assert_agrees(HONEST, EXPECT_HONEST);
}

#[test]
fn independent_traversal_agrees_with_the_ledger_on_the_unanchored_pack() {
    assert_agrees(T3, EXPECT_T3);
}

#[test]
fn independent_traversal_agrees_with_the_ledger_under_witness_quarantine() {
    assert_agrees(FORK_WITNESS, EXPECT_FORK);
}

// ---------------------------------------------------------------------------
// Fuzzing: no pack byte-string panics, from raw bytes all the way to a verdict
// ---------------------------------------------------------------------------

const FIXTURES: [&[u8]; 6] = [HONEST, T1, T2, T3, FORK_WITNESS, EARLIEST_HELD];

/// Every path from raw pack bytes to a verdict, over one input. Return values
/// are ignored — the property is only that none of these aborts.
fn run_every_path(bytes: &[u8]) {
    let _ = parse_pack(bytes, org());
    let _ = parse_pack(bytes, PubKey([0u8; 32]));
    let _ = verify(bytes, org());
    let _ = verify(bytes, PubKey([0xabu8; 32]));
}

proptest! {
    /// Arbitrary bytes. Short inputs weighted in, because truncation bugs live
    /// at the head-parsing boundary.
    #[test]
    fn arbitrary_bytes_never_panic(bytes in proptest::collection::vec(any::<u8>(), 0..400)) {
        run_every_path(&bytes);
    }

    /// Bytes with the pack marker prepended — this forces the fuzzer past step 1
    /// and into the envelope decoder and the per-object self-check.
    #[test]
    fn marked_garbage_never_panics(tail in proptest::collection::vec(any::<u8>(), 0..400)) {
        let mut bytes = vigil_verify::PACK_MARKER.to_vec();
        bytes.extend_from_slice(&tail);
        run_every_path(&bytes);
    }

    /// Single-byte mutations of a real fixture. These reach deepest, because the
    /// frame stays structurally plausible: an envelope that decodes, carried
    /// objects that nearly self-check, a DAG that nearly builds.
    #[test]
    fn single_byte_mutations_of_a_fixture_never_panic(
        which in 0usize..FIXTURES.len(),
        index in any::<prop::sample::Index>(),
        delta in 1u8..=255,
    ) {
        let mut bytes = FIXTURES[which].to_vec();
        let i = index.index(bytes.len());
        bytes[i] = bytes[i].wrapping_add(delta);
        run_every_path(&bytes);
    }

    /// Truncation of a real fixture at every offset.
    #[test]
    fn truncation_of_a_fixture_never_panics(
        which in 0usize..FIXTURES.len(),
        index in any::<prop::sample::Index>(),
    ) {
        let bytes = FIXTURES[which];
        let cut = index.index(bytes.len() + 1);
        run_every_path(&bytes[..cut]);
    }

    /// Splicing two fixtures at arbitrary points — a well-formed prefix followed
    /// by a well-formed-elsewhere suffix, the classic way to smuggle a
    /// length/'`prev`'/`acks` inconsistency past early checks.
    #[test]
    fn spliced_fixtures_never_panic(
        a in 0usize..FIXTURES.len(),
        b in 0usize..FIXTURES.len(),
        ai in any::<prop::sample::Index>(),
        bi in any::<prop::sample::Index>(),
    ) {
        let (fa, fb) = (FIXTURES[a], FIXTURES[b]);
        let mut bytes = fa[..ai.index(fa.len() + 1)].to_vec();
        bytes.extend_from_slice(&fb[bi.index(fb.len() + 1)..]);
        run_every_path(&bytes);
    }
}
