//! Expected-verdict generator for `vigil-verify`'s cross-check
//! (`spec/03-export-pack.md` §8: "`vigil-verify`'s recomputed bracket for a
//! claim equals `vigil-ledger`'s `bracket()` over the same object set").
//!
//! `vigil-verify` may not link `vigil-ledger` — the independence rule is the
//! whole point of that crate (`crates/vigil-verify/src/lib.rs`). So the ledger's
//! side of that equality is computed here, once, and written to
//! `testdata/packs/expected/` as static JSON. `vigil-verify`'s property test
//! loads that file and asserts its own independent traversal agrees.
//!
//! Run with `cargo run -p vigil-ledger --example gen_pack_verdicts`. Like
//! `gen_packs`, it is deterministic and CI regenerates then diffs: a checked-in
//! verdict the generator no longer produces is a `bracket()` behaviour change
//! and must not pass silently.

#[path = "../testsupport/pack_scenarios.rs"]
mod pack_scenarios;

use std::fmt::Write as _;
use std::path::PathBuf;

use vigil_ledger::{
    Bracket, ChainVerification, Dag, MemoryStore, Quarantine, Store, WindowEdge, parse_pack,
    verify_chain,
};

fn store_from_pack(pack: &vigil_ledger::PackContents) -> MemoryStore {
    let mut s = MemoryStore::new();
    for (_, obs, sig) in pack.valid_observations() {
        s.put_observation(obs, sig).expect("put observation");
    }
    for (_, att, sig) in pack.valid_attestations() {
        s.put_attestation(att, sig).expect("put attestation");
    }
    s
}

fn edge_json(e: WindowEdge) -> String {
    match e {
        WindowEdge::Attestation(h) => format!("{{\"attestation\":\"{h}\"}}"),
        WindowEdge::Genesis => "\"genesis\"".to_owned(),
        WindowEdge::VerificationMoment => "\"verification_moment\"".to_owned(),
    }
}

fn bracket_json(b: &Bracket) -> String {
    let opt =
        |o: Option<vigil_core::Hash>| o.map_or_else(|| "null".to_owned(), |h| format!("\"{h}\""));
    format!(
        "{{\"observation\":\"{}\",\"sealed\":{},\"witness_depth\":{},\"upper_bound\":{},\
         \"lower_bound\":{},\"window_lower\":{},\"window_upper\":{},\"disputed\":{}}}",
        b.observation,
        b.sealed,
        b.witness_depth,
        opt(b.upper_bound),
        opt(b.lower_bound),
        edge_json(b.unwitnessed_window.lower),
        edge_json(b.unwitnessed_window.upper),
        b.disputed,
    )
}

fn chain_json(v: &ChainVerification) -> String {
    match v {
        ChainVerification::Verified => "\"verified\"".to_owned(),
        ChainVerification::Incomplete { missing } => {
            let ms: Vec<String> = missing.iter().map(u64::to_string).collect();
            format!("{{\"incomplete\":[{}]}}", ms.join(","))
        }
        ChainVerification::Violated(_) => "\"violated\"".to_owned(),
    }
}

/// One fixture: the pack file, the claim, and whether a fork proof it carries
/// should be applied as a quarantine before bracketing.
struct Case {
    name: &'static str,
    pack: Vec<u8>,
    claim: vigil_core::Hash,
    author: vigil_core::PubKey,
    apply_carried_forks: bool,
}

fn cases() -> Vec<Case> {
    let h = pack_scenarios::Honest::build();
    let a = vigil_core::public_key(&h.a);
    vec![
        Case {
            name: "honest",
            pack: pack_scenarios::honest_pack(),
            claim: h.claim(),
            author: a,
            apply_carried_forks: false,
        },
        Case {
            name: "t3-dropped-anchor",
            pack: pack_scenarios::t3_dropped_anchor(),
            claim: h.claim(),
            author: a,
            apply_carried_forks: false,
        },
        Case {
            name: "fork-witness",
            pack: pack_scenarios::fork_witness_pack(),
            claim: h.claim(),
            author: a,
            apply_carried_forks: true,
        },
    ]
}

fn main() {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../testdata/packs/expected");
    std::fs::create_dir_all(&dir).expect("create testdata/packs/expected");

    for case in cases() {
        let pack = parse_pack(&case.pack).expect("fixture pack parses");
        let store = store_from_pack(&pack);

        let mut quarantine = Quarantine::new();
        if case.apply_carried_forks {
            for fp in &pack.fork_proofs {
                if let Ok(checked) = fp.check() {
                    quarantine.apply(&checked);
                }
            }
        }

        let dag = Dag::build(&store, &quarantine).expect("dag build");
        let chain = verify_chain(&store, &case.author).expect("chain check");

        let bracket = dag
            .bracket(case.claim)
            .map_or_else(|| "null".to_owned(), |b| bracket_json(&b));

        let mut json = String::new();
        writeln!(json, "{{").unwrap();
        writeln!(
            json,
            "  \"note\": \"generated by `cargo run -p vigil-ledger --example \
             gen_pack_verdicts` — vigil-verify cross-checks its independent \
             traversal against this\","
        )
        .unwrap();
        writeln!(json, "  \"claim\": \"{}\",", case.claim).unwrap();
        writeln!(json, "  \"author\": \"{}\",", case.author).unwrap();
        writeln!(json, "  \"chain\": {},", chain_json(&chain)).unwrap();
        writeln!(json, "  \"bracket\": {bracket}").unwrap();
        writeln!(json, "}}").unwrap();

        let path = dir.join(format!("{}.json", case.name));
        std::fs::write(&path, &json).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
        println!("{:<20} {} bytes", case.name, json.len());
    }
}
